$CONSOLE:ONLY

OPTION _EXPLICIT

CONST TEXT_HELLO = "Hello"
CONST TEXT_WORLD = "world"
CONST TEXT_ASCII = CHR$(176) + CHR$(177) + CHR$(178) + " " + TEXT_HELLO + " " + TEXT_WORLD + " " + CHR$(178) + CHR$(177) + CHR$(176)


_CLIPBOARD$ = TEXT_HELLO
_CLIPBOARD$ = TEXT_WORLD

PRINT "Set: "; TEXT_WORLD
PRINT "Got: "; _CLIPBOARD$

_CLIPBOARD$ = TEXT_ASCII

IF TEXT_ASCII = _CLIPBOARD$ THEN
    PRINT "Test passed"
ELSE
    PRINT "Test failed"
END IF

SYSTEM
