$CONSOLE:ONLY

OPTION _EXPLICIT

CONST TEXT_FAIL = "Failed"
CONST TEXT_PASS = "Passed"
CONST TEXT_ASCII = CHR$(176) + CHR$(177) + CHR$(178) + " " + TEXT_PASS + " " + CHR$(178) + CHR$(177) + CHR$(176)

PRINT "Clipboard set test: ";

_CLIPBOARD$ = TEXT_FAIL
_CLIPBOARD$ = TEXT_PASS

IF TEXT_PASS = _CLIPBOARD$ THEN
    PRINT TEXT_PASS
ELSE
    PRINT TEXT_FAIL
END IF

PRINT "Clipboard extended ASCII set test: ";

_CLIPBOARD$ = TEXT_ASCII

IF TEXT_ASCII = _CLIPBOARD$ THEN
    PRINT TEXT_PASS
ELSE
    PRINT TEXT_FAIL
END IF

PRINT "Clipboard clear test: ";

_CLIPBOARD$ = TEXT_FAIL
_CLIPBOARD$ = ""

IF "" = _CLIPBOARD$ THEN
    PRINT TEXT_PASS
ELSE
    PRINT TEXT_FAIL
END IF

SYSTEM
