$CONSOLE:ONLY

PRINT
PRINT "("; _TOSTR$(_SINGLE_MIN); ")"
PRINT "("; _TOSTR$(_SINGLE_MAX); ")"
PRINT
PRINT "("; _TOSTR$(_DOUBLE_MIN); ")"
PRINT "("; _TOSTR$(_DOUBLE_MAX); ")"
PRINT
PRINT "("; _TOSTR$(_FLOAT_MIN); ")"
PRINT "("; _TOSTR$(_FLOAT_MAX); ")"

SYSTEM

