$CONSOLE
_DEST _CONSOLE

_SCREENHIDE
PRINT _DESKTOPHEIGHT > 0
PRINT _DESKTOPWIDTH > 0
_ICON
PRINT "Got Past Icon!"
_MOUSEHIDE
PRINT "Got Past MouseHide!"
_MOUSESHOW
PRINT "Got Past MouseShow!"
PRINT _SCREENEXISTS
PRINT _SCREENICON <> 0
PRINT _SCREENX >= 0
PRINT _SCREENY >= 0
_TITLE "foobar"
PRINT "Title: "; _TITLE$
PRINT _WINDOWHANDLE <> 0
PRINT _WINDOWHASFOCUS <= 0 ' This can be a bit random
_SCREENSHOW
PRINT "Got past ScreenShow!"
SYSTEM
