$IF WINDOWS OR MACOSX THEN
    ' GLFW cannot create a window with OpenGL context in a macOS and Windows GitHub runner
    $CONSOLE:ONLY
    PRINT _TRUE
    SYSTEM
$END IF

$CONSOLE
_DEST _CONSOLE

PRINT _WINDOWHANDLE <> 0
PRINT _WINDOWHANDLE(0) <> 0
PRINT _WINDOWHANDLE(1) <> 0
PRINT _WINDOWHANDLE(2) <> 0

SYSTEM
