name: PR

on:
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  PR-Run:
    uses: ./.github/workflows/build-process.yml
    secrets: inherit
